spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddisk
    username: root
    password: xiaopengfei
  sql:
    init:
      mode: always


logging:
  level:
    sql: trace
server:
  http2:
    enabled: true
  ssl:
    key-alias: tomcat
    key-store: ./keystore.p12
    keyStoreType: PKCS12
    key-store-password: xiaopengfei
  # https://docs.spring.io/spring-cloud-skipper/docs/1.0.0.BUILD-SNAPSHOT/reference/html/configuration-security-enabling-https.html
