spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddisk
    username: u_doc
    password: 123456
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: false
  sql:
    init:
      mode: always
cas:
  single-logout:
    enabled: true
  authentication-url-patterns:
    - /login/cas
  server-login-url: https://ids.xidian.edu.cn/authserver/login
  client-host-url: https://seedoc.xidian.edu.cn:443
  server-url-prefix: https://ids.xidian.edu.cn/authserver


logging:
  level:
    sql: trace
server:
  error:
    include-stacktrace: never

  port: 8000
